MEDIA_DIR_SERIES = "/disk/media/series/"
MEDIA_DIR_FILMS = "/disk/media/anime_films/"
TORRENT_DIR = "/disk/torrents/"
DISABLE_NEW_ANIME = False
ACCOUNT = ""
MIN_SERIES_SIZE = 3  # the minimum accepted size of TV shows in GiB
INDEXER_KEYWORDS = ["blu-ray", "blu ray", "(bd", "[bd", "bdrip"]  # results containing these in the title get a rank boost
INDEXER_QUALITY = "1080p"  # preferred quality. Not a hard limit.
INDEXER_GROUPS = ["commie", "erai-raws", "horriblesubs", "subsplease"]  # preferred release groups
INTERVAL = 10 * 60  # in seconds
