services:
  apache:
    build:
      context: .
      dockerfile: ./dockerfiles/apache/Dockerfile
    ports:
      - "5030:80"

  flood:
    hostname: flood
    image: jesec/flood
    user: 1000:1000
    restart: unless-stopped
    command: --port 3000
    environment:
      HOME: /config
    volumes:
      - ./rtorrent_config:/config
      - ${MEDIA_DIR_SERIES}:/series
      - ${MEDIA_DIR_FILMS}:/films
      - ${TORRENT_DIR}:/torrents
    ports:
      - "50000:50000"
      - "50000:50000/udp"
      - "7777:7777"
      - "6969:6969"
      - "6969:6969/udp"
      - "80:80"
      - "80:80/udp"
      - "1337:1337/udp"
      - "451:451/udp"
      - "6881:6881"
      - "6881:6881/udp"

  rtorrent:
    image: jesec/rtorrent
    user: 1000:1000
    restart: unless-stopped
    command: -o network.port_range.set=50000-50000,system.daemon.set=true
    ports:
      - "50000:50000"
      - "50000:50000/udp"
    environment:
      HOME: /config
    volumes:
      - ./rtorrent_config:/config
      - ${MEDIA_DIR_SERIES}:/series
      - ${MEDIA_DIR_FILMS}:/films
      - ${TORRENT_DIR}:/torrents

  aniscraper:
    build:
      context: .
      dockerfile: ./dockerfiles/aniscraper/Dockerfile
    volumes:
      - ./rtorrent_config:/config
      - ${MEDIA_DIR_SERIES}:/series
      - ${MEDIA_DIR_FILMS}:/films
      - ${TORRENT_DIR}:/torrents
    depends_on:
      - "rtorrent"

  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./sonarr_data:/config
      - ${MEDIA_DIR_SERIES}:/tv
      - ${TORRENT_DIR}:/torrents
    ports:
      - 8989:8989
      
