services:
  openvpn:
    build:
      context: .
      dockerfile: ./dockerfiles/openvpn/Dockerfile
      args: 
        - OPENVPN_PROFILE_PATH=${OPENVPN_PROFILE_PATH}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 8.8.4.4
    tty: true
    stdin_open: true
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
    ports:
      - "50000:50000"
      - "50000:50000/udp"
      - "7777:7777"
      - "6969:6969"
      - "6969:6969/udp"
      - "80:80"
      - "80:80/udp"
      - "1337:1337/udp"
      - "451:451/udp"
      - "6881:6881"
      - "6881:6881/udp"

  flood:
    hostname: flood
    image: jesec/flood
    user: 1000:1000
    restart: unless-stopped
    command: --port 3000
    environment:
      HOME: /config
    volumes:
      - ./rtorrent_config:/config
      - ${DOCKER_SERIES}:/series
      - ${DOCKER_FILMS}:/films
      - ${DOCKER_TORRENTS}:/torrents
    ports:
      - 0.0.0.0:3000:3000

  rtorrent:
    image: jesec/rtorrent
    user: ${DOCKER_USER}:${DOCKER_GROUP}
    restart: unless-stopped
    command: -o network.port_range.set=50000-50000,system.daemon.set=true
    environment:
      HOME: /config
    volumes:
      - ./rtorrent_config:/config
      - ${SERIES}:/series
      - ${FILMS}:/films
      - ${TORRENTS}:/torrents
    network_mode: "service:openvpn"
    depends_on:
      - "openvpn"

  aniscraper:
    build:
      context: .
      dockerfile: ./dockerfiles/aniscraper/Dockerfile
    volumes:
      - ./rtorrent_config:/config
      - ./anime_ids.json:/app/anime_ids.json
      - ${SERIES}:/series
      - ${FILMS}:/films
      - ${TORRENTS}:/torrents
    depends_on:
      - "rtorrent"

  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./sonarr_data:/config
      - ${SERIES}:/tv
      - ${TORRENTS}:/torrents
    ports:
      - 8989:8989
