services:
  openvpn:
    build:
      context: .
      dockerfile: ./dockerfiles/openvpn/Dockerfile
      args: 
        - OPENVPN_PROFILE_PATH=${OPENVPN_PROFILE_PATH}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "50000:50000"
      - "50000:50000/udp"

  apache:
    build:
      context: .
      dockerfile: ./dockerfiles/apache/Dockerfile
    ports:
      - "5030:80"

  flood:
    hostname: flood
    image: jesec/flood
    user: 1000:1000
    restart: unless-stopped
    command: --port 3000
    environment:
      HOME: /config
    volumes:
      - ./rtorrent_config:/config
      - ${MEDIA_DIR_SERIES}:/series
      - ${MEDIA_DIR_FILMS}:/films
      - ${TORRENT_DIR}:/torrents
    ports:
      - 0.0.0.0:3000:3000

  rtorrent:
    image: jesec/rtorrent
    user: ${DOCKER_USER}:${DOCKER_GROUP}
    restart: unless-stopped
    command: -o network.port_range.set=50000-50000,system.daemon.set=true
    environment:
      HOME: /config
    volumes:
      - ./rtorrent_config:/config
      - ${MEDIA_DIR_SERIES}:/series
      - ${MEDIA_DIR_FILMS}:/films
      - ${TORRENT_DIR}:/torrents
    network_mode: "service:openvpn"
    depends_on:
      - "openvpn"

  aniscraper:
    build:
      context: .
      dockerfile: ./dockerfiles/aniscraper/Dockerfile
    volumes:
      - ./rtorrent_config:/config
      - ./anime_ids.json:/app/anime_ids.json
      - ${MEDIA_DIR_SERIES}:/series
      - ${MEDIA_DIR_FILMS}:/films
      - ${TORRENT_DIR}:/torrents
    depends_on:
      - "rtorrent"

  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./sonarr_data:/config
      - ${MEDIA_DIR_SERIES}:/tv
      - ${TORRENT_DIR}:/downloads
    ports:
      - 8989:8989
